[Transfer]
Verify=false

[Source]
Type=url-file
Path=https://pratikp24.github.io/sysext-bakery/extensions/zerotier/
MatchPattern=zerotier-@v-%a.raw

[Target]
InstancesMax=3
Type=regular-file
Path=/opt/extensions/zerotier
CurrentSymlink=/etc/extensions/zerotier.raw
