[Transfer]
Verify=false

[Source]
Type=url-file
Path=https://pratikp24.github.io/sysext-bakery/extensions/cloudflared/
MatchPattern=cloudflared-@v-%a.raw

[Target]
InstancesMax=3
Type=regular-file
Path=/opt/extensions/cloudflared
CurrentSymlink=/etc/extensions/cloudflared.raw
